### ISSUE TITLE
BPMC data link

### ISSUE THREAD

**Issue by hkoohy** [theislab/scanpy_usage#1]
Hi, sorry to bother you again,
It looks like that the BPMC link here https://github.com/theislab/scanpy_usage/tree/master/170505_seurat
directs to brain dataset in 10 x genomics (1.3 cells) whereas I was I expecting 2700 Peripheral Blood Mononuclear Cells! 
Is this a typo or I am overlooking something?
thanks
Hashem

**Comment by falexwolf** [comment]
Hi Hashem,
no worries! There was already a link to the specific dataset in the notebook, but not in the readme. I now added [it](https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/pbmc3k).
Cheers,
  Alex
