### ISSUE TITLE
unable to find genes when export to SPRING object

### ISSUE THREAD

**Issue by MichaelPeibo** [theislab/scanpy_usage#14]
Hi scanpy team,
I convert Seurat obj to anndata with:
`mda_ad <- Convert(from = mda, to = "anndata",filename = 'mda_day27_ad.h5ad')`

> 
> mda_ad
AnnData object with n_obs × n_vars = 6039 × 19331 
    obs: 'n_genes', 'n_counts', 'orig_ident', 'percent_mito', 'S_Score', 'G2M_Score', 'Phase', 'old_ident', 'res_1_2'
    var: 'gene.mean', 'gene.dispersion', 'gene.dispersion.scaled'
    obsm: 'X_pca', 'X_tsne'

Then I run as scanpy's tutorial https://github.com/theislab/scanpy_usage/blob/master/171111_SPRING_export/SPRING_export.ipynb
to export SPRING, however, I was unable to find no response when I enter a gene in the web browser. 
I have all required files in the folder.
![image](https://user-images.githubusercontent.com/32219336/54064912-58710a00-4254-11e9-8ee3-b4d13a43d786.png)
![image](https://user-images.githubusercontent.com/32219336/54064914-5eff8180-4254-11e9-8d57-f12bb8c56c08.png)

Any suggestion how to solve it?

Thanks!

![image](https://user-images.githubusercontent.com/32219336/54035115-8a9e4f80-41f3-11e9-998d-326df9fcf89a.png)

**Comment by falexwolf** [comment]
I fear you have to address the Spring authors directly, @swolock, for instance, who wrote the exporter.

If it continues to be buggy, you might also look at [cellxgene](https://github.com/chanzuckerberg/cellxgene), which is very professionally developed and directly reads in Scanpy's `h5ad` files.

**Comment by swolock** [comment]
Hi @MichaelPeibo, 

It's possible there's an unknown SPRING bug behind your issue, in which case the easiest way for me to help would be for you to share your SPRING folder with me (if this is possible). But before doing that, answers to the following questions might help me narrow it down: 

- Can you confirm you're using Python 2 to start the local server? 
- Would you mind sharing the output from the console/terminal that is running the server? 
- What is the exact URL you entered?

And @falexwolf -- thanks for referring the issue to me!

**Comment by MichaelPeibo** [comment]
Hi @falexwolf Thanks for pointing it out.

Hi @swolock 
I went through it today.
I guess it may be due to the multiple web server error when I first start it?

Or maybe both my server and me need a rest and restart.....

Sorry to bother, very nice interactive tool!!!

**Comment by MichaelPeibo** [comment]
@falexwolf @swolock  
Hi, I recheck my web history, I doubted that it is due to old springViewer I used.
I followed this tutorial https://github.com/theislab/scanpy_usage/blob/master/171111_SPRING_export/SPRING_export.ipynb
and it gave the link is http://localhost:8000/<SPRING_INSTALLATION>/springViewer.html?<Relative_Path_To_SPRING_PROJECT>

However, I got through it with http://localhost:8000/springViewer_1_6_dev.html?
