### ISSUE TITLE
Louvain method raises segmentation fault 

### ISSUE THREAD

**Issue by anilbey** [theislab/scanpy_usage#2]
Hello, 
I am running the "zheng17_pbmc68k_cellranger_Py.ipynb" notebook and I am having a segmentation fault error when I try to run the code below:
`sc.tl.louvain(adata, resolution=1.2)`

I performed the test cases provided by the [louvain-igraph package](https://github.com/vtraag/louvain-igraph/tree/master/tests). They both work fine.
My scanpy version is 0.4.2
My louvain version is 0.6.1

Do you know what the cause of this error might be?
Thanks in advance,
anilbey

**Comment by falexwolf** [comment]
Sorry to read this... Hm, no one reported it before. You need some memory for processing 70 000 cells, but it's absolutely no problem on my a 2.5-year-old mac with 16 GB memory and the laptops of several other users. Without logging files etc. I cannot help you more. Set `sc.settings.logging = 3` or higher...

What happens for the standard Seurat tutorial? https://github.com/theislab/scanpy_usage/tree/master/170505_seurat

If the memory problem appears when constructing the graph: we're currently working on an even more efficient method for that.

**Comment by flying-sheep** [comment]
to elaborate: in some cases a segfault means exactly that: the process failed to allocate memory because it’s full. it often means other things (i.e. actual bugs) in C or C++ applications.

but if alex encountered problems with out of memory segfaults before, that’s probably it.

**Comment by falexwolf** [comment]
I'd assume you get a segfault on a laptop when constructing the graph for 1M cells but have not experienced it.

I doubt that the segfault is raised due to access of invalid pointer addresses... there should be no such bug...

**Comment by anilbey** [comment]
Hi, the same thing happens on the seurat notebook as well. 

It shouldn't be related to the memory. I'm running it on a server having 128GB of memory.

**Comment by falexwolf** [comment]
Ok, this is very strange... But as I said, I cannot help if you do not provide the logging info... and the Scanpy version.

**Comment by anilbey** [comment]
Thanks, actually now I'm trying to create the log file. 
Should I do it this way and expect for the methods to log the file?

```
sc.logging.print_version_and_date()
sc.logging.print_versions_dependencies_numerics()
sc.settings.logging = 3 
sc.settings.log_file = './seuratlogfile.txt'
```
But the log file is not created on the same directory. 
 
Meanwhile, here is the version information.
> Running Scanpy 0.4.2 on 2018-01-31 11:46.
Dependencies: numpy==1.14.0 scipy==1.0.0 pandas==0.22.0 scikit-learn==0.19.1 statsmodels==0.8.0 python-igraph==0.7.1 louvain==0.6.1

**Comment by falexwolf** [comment]
Thanks! You don't have to set a log file (even though it should work the way you did it). You can't just send me the logging output that is written to the standard output. Run the notebook for `sc.settings.logging = 4`. Also, does `sc.tl.diffmap` run without a problem?

**Comment by anilbey** [comment]
Alright, it runs smoothly now. Thank you for all your help!

To sum up:

- The method works perfectly fine with both the _pip_ and the _conda-forge_ installations of the _igraph_ package on my local machine.
- The method only works with the _pip_ installation of _python-igraph_ on the server (_conda-forge_ installation raises exception).

I suspect some of the dependencies cannot be installed or compiled through conda on the server since I lack the root privilege. I am also curious to hear your opinion on this manner.
