### ISSUE TITLE
Can't download bulk labels in project example zheng17

### ISSUE THREAD

**Issue by PhungVanDuy** [theislab/scanpy_usage#3]
Dear @falexwolf and Scanpy Team!
I can't download bulk labels as you mentioned at [Zheng17 Project](https://github.com/theislab/scanpy_usage/blob/master/170503_zheng17/zheng17.ipynb). 
![image](https://user-images.githubusercontent.com/28798474/39882848-354e4d1e-54af-11e8-93f6-6f0641addc8f.png)
Can you re-upload file bulk.txt? 
I will be very grateful to you!

**Comment by falexwolf** [comment]
Sorry about this! This disappeared when restructuring the repo.  I added the assets again.
