### ISSUE TITLE
Incorrect reference doi in seurat.ipynb

### ISSUE THREAD

**Issue by ld2113** [theislab/scanpy_usage#7]
Hi there,
Thank you for the nice tutorials.

I was just going through the seurat.ipynb tutorial and found that one of the reference links seems to be broken.

In the "Clustering the graph" Section, the first reference ("Levine et al. (2015)") should point to https://doi.org/10.1016/j.cell.2015.05.047

Currently it produces an DOI not found Error (seems like the last character from the URL is missing in the notebook).

**Comment by falexwolf** [comment]
Thank you, will be resolved in the next version of the tutorial.
